
import "./globals.css";




export const metadata = {
  title: "Safar-Land",
  description: "Generated by Saman Karimi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
      >
        {children}
      </body>
    </html>
  );
}
